"""add duplicate_of to answers

Revision ID: 49a7fb55da73
Revises: 8b3e7424df24
Create Date: 2026-08-11 17:17:54.500430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a7fb55da73'
down_revision: Union[str, Sequence[str], None] = '8b3e7424df24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('duplicate_of', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answers', 'answers', ['duplicate_of'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'duplicate_of')
    # ### end Alembic commands ###
