"""add adaptive difficulty to interviews

Revision ID: 8b3e7424df24
Revises: 3d19a6d1e0ae
Create Date: 2026-08-11 10:05:52.627723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b3e7424df24'
down_revision: Union[str, Sequence[str], None] = '3d19a6d1e0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('current_difficulty', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'current_difficulty')
    # ### end Alembic commands ###
